import product1 from './assets/products/product-1.jpeg';
import product2 from './assets/products/product-2.jpeg';
import product3 from './assets/products/product-3.jpeg';
import product4 from './assets/products/product-4.jpeg';
import product5 from './assets/products/product-5.jpeg';
import product6 from './assets/products/product-6.jpeg';
import product7 from './assets/products/product-7.jpeg';
import product8 from './assets/products/product-8.jpeg';
import product9 from './assets/products/product-9.jpeg';
import product10 from './assets/products/product-10.jpeg';
import product11 from './assets/products/product-11.jpeg';
import product12 from './assets/products/product-12.jpeg';
import product13 from './assets/products/product-13.jpeg';
import product14 from './assets/products/product-14.jpeg';
import product15 from './assets/products/product-15.jpeg';
import product16 from './assets/products/product-16.jpeg';
import product17 from './assets/products/product-17.jpeg';
import product18 from './assets/products/product-18.jpeg';
import product19 from './assets/products/product-19.jpeg';
import product20 from './assets/products/product-20.jpeg';
import product21 from './assets/products/product-21.jpeg';
import product22 from './assets/products/product-22.jpeg';

export const PRODUCTS = [
    {
        id:1,
        productName: "accent chair",
        price:259.99,
        productImage:product1,
        category: "office",
        company: "marcos",
        colors: ["red","green","blue"],
        freeShiping: true,
    },
    {
        id:2,
        productName: "albany sectional",
        price:1009.99,
        productImage:product2,
        category: "living-room",
        company: "liddy",
        colors:  ["grey"],
        freeShiping: false,
      },
      {
        id:3,
        productName: "albany table",
        price:3099.99,
        productImage:product3,
        category: "kitchen",
        company: "liddy",
        colors:  ["yellow","blue"],
        freeShiping: false,
      },
      {
        id:4,
        productName: "armchair",
        price:125.99,
        productImage:product4,
        category: "bedroom",
        company: "marcos",
        colors:  ["black","green", "blue"],
        freeShiping: true,
      },
      {
        id:5,
        productName: "dining table",
        price:429.99,
        productImage:product5,
        category: "dining",
        company: "ikea",
        colors:  ["red","green", "blue"],
        freeShiping: true,
      },
      {
        id:6,
        productName: "emperor bed",
        price:239.99,
        productImage:product6,
        category: "bedroom",
        company: "ikea",
        colors:  ["none"],
        freeShiping: true,
      },
      {
        id:7,
        productName: "entertainment center",
        price:399.99,
        productImage:product7,
        category: "living-room",
        company: "caressa",
        colors:  ["red","black"],
        freeShiping: true,
      },
      {
        id:8,
        productName: "high-back bench",
        price:429.99,
        productImage:product8,
        category: "office",
        company: "ikea",
        colors:  ["black","green"],
        freeShiping: true,
      },
      {
        id:9,
        productName: "leather chair",
        price:200.99,
        productImage:product9,
        category: "bedroom",
        company: "caressa",
        colors:  ["red","green", "yellow"],
        freeShiping: false,
      },
      {
        id:10,
        productName: "leather sofa",
        price:999.99,
        productImage:product10,
        category: "office",
        company: "caressa",
        colors:  ["green", "blue"],
        freeShiping: false,
      },
      {
        id:11,
        productName: "modern bookshelf",
        price:319.99,
        productImage:product11,
        category: "kids",
        company: "caressa",
        colors:  ["red","green", "yellow"],
        freeShiping: false,
      },
      {
        id:12,
        productName: "modern poster",
        price:30.99,
        productImage:product12,
        category: "living-room",
        company: "liddy",
        colors:  ["black"],
        freeShiping: true,
      },
      {
        id:13,
        productName: "shelf",
        price:309.99,
        productImage:product13,
        category: "living-room",
        company: "ikea",
        colors:  ["green"],
        freeShiping: false,
      },
      {
        id:14,
        productName: "simple chair",
        price:1099.99,
        productImage:product14,
        category: "living-room",
        company: "liddy",
        colors:  ["blue"],
        freeShiping: true,
      },
      {
        id:15,
        productName: "sofa set",
        price:1229.99,
        productImage:product15,
        category: "living-room",
        company: "marcos",
        colors:  ["green", "yellow"],
        freeShiping: true,
      },
      {
        id:16,
        productName: "suede armchair",
        price:159.99,
        productImage:product16,
        category: "office",
        company: "caressa",
        colors:  ["yellow"],
        freeShiping: false,
      },
      {
        id:17,
        productName: "utopia sofa",
        price:799.99,
        productImage:product17,
        category: "living-room",
        company: "liddy",
        colors:  ["red","green"],
        freeShiping: false,
      },
      {
        id:18,
        productName: "vase table",
        price:1209.99,
        productImage:product18,
        category: "office",
        company: "marcos",
        colors:  ["red"],
        freeShiping: false,
      },
      {
        id:19,
        productName: "wooden bed",
        price:2500.99,
        productImage:product19,
        category: "bedroom",
        company: "ikea",
        colors:  ["black","yellow"],
        freeShiping: false,
      },
      {
        id:20,
        productName: "wooden desk",
        price:1509.99,
        productImage:product20,
        category: "office",
        company: "ikea",
        colors:  ["black"],
        freeShiping: true,
      },
      {
        id:21,
        productName: "wooden desk",
        price:400.99,
        productImage:product21,
        category: "office",
        company: "ikea",
        colors:  ["green", "blue"],
        freeShiping: false,
      },
      {
        id:22,
        productName: "wooden table",
        price:2349.99,
        productImage:product22,
        category: "kitchen",
        company: "caressa",
        colors:  ["red","yellow"],
        freeShiping: true,
      },
];